# Site settings
title: AKA Praha
description: Akademie klinick√© anatomie Praha
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aka-praha.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
